version: 2
updates:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry - checks daily
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
